{% set name = "gmx_MMPBSA" %}
{% set version = "1.6.3" %}
{% set sha256 = "c0e92afb48923bd03efa312a6707912f639e1597fb84769a449e4de2a375351f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  entry_points:
     - gmx_MMPBSA = GMXMMPBSA.app:gmxmmpbsa
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas 1.2.2
    - seaborn <0.12
    - mpi4py <=3.1.5
    - scipy >=1.6.1
    - ambertools >=20
    - matplotlib-base 3.5.2
    - h5py
    - gromacs
    - tqdm

test:
  imports:
    - GMXMMPBSA
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - gmx_MMPBSA -h

about:
  home: https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: "gmx_MMPBSA is a new tool based on AMBER's MMPBSA.py aiming to perform end-state free energy calculations with GROMACS files."
  description: |
    gmx_MMPBSA is a new tool based on AMBER's MMPBSA.py aiming to perform end-state free energy calculations with 
    GROMACS files. It works with all GROMACS versions along with AmberTools20 or 21 and brings improvements in 
    compatibility, versatility, analyses, and parallelization compared to existing programs. 
    Multiple calculations can be performed with gmx_MMPBSA such as Normal binding free energies, Alanine scanning, 
    Decomposition schemes, Entropy corrections, Stability and QM/MMGBSA
  doc_url: https://valdes-tresanco-ms.github.io/gmx_MMPBSA
  dev_url: https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA

extra:
  recipe-maintainers:
    - Valdes-Tresanco-MS
    - marioernestovaldes
